SHIPMENT_SERVICE_PROVIDER_UPS = 'ups'
SHIPMENT_SERVICE_PROVIDER_FEDEX = 'fedex'
SHIPMENT_SERVICE_PROVIDER_DHL = 'dhl'
SHIPMENT_SERVICE_PROVIDER_USPS = 'usps'

SHIPMENT_SERVICE_PROVIDER_CHOICES = (
    (SHIPMENT_SERVICE_PROVIDER_UPS, 'UPS'),
    (SHIPMENT_SERVICE_PROVIDER_FEDEX, 'FedEx'),
    (SHIPMENT_SERVICE_PROVIDER_DHL, 'DHL'),
    (SHIPMENT_SERVICE_PROVIDER_USPS, 'USPS'),
)

TRACKING_NUMBER_PATTERN_UPS = "^1Z[0-9A-Z]{16,19}$"
TRACKING_NUMBER_PATTERN_FEDEX = "^[\d]{9,15}$"
TRACKING_NUMBER_PATTERN_DHL = "^[\d]{7}|[A-Z]{3}[0-9]{5,7}$"
TRACKING_NUMBER_PATTERN_USPS = "^91[\d]{18,20}|[A-Za-z]{2}[0-9]+US|[\d]{30}$"
